apiVersion: v1
kind: Deployment
metadata:
  name: bots-deployment
spec:
  selector:
    matchLabels:
      app: bots
  replicas: 2
  template:
    metadata:
      labels:
        app: bots
    spec:
      containers:
        - name: resume-bot
          image: phella/resume_bot
          ports:
            - containerPort: 80
        - name: translate-bot
          image: phella/translate_bot
          ports:
            - containerPort: 8080