apiVersion: v1
kind: Pod
metadata:
  name: bots_pod
  labels:
    env: prod
    app: bots
    tier: backend
    owner: Ilshat
spec:
  containers:
    - name: resume_bot
      image: phella/resume_bot
      ports:
        - containerPort: 80
    - name: translate_bot
      image: phella/translate_bot
      ports:
        - containerPort: 8080